### ISSUE TITLE
Checklist for version release

### ISSUE THREAD

**Issue by verku** [NBISweden/GenErode#91]
- [ ] Feature branches merged into dev
- [ ] Test runs finished successfully (github and on cluster)
- [ ] Changelog updated
- [ ] Version number updated in `Snakefile` and `config/config.yaml`
- [ ] If needed, pipeline documentation updated
- [ ] dev merged into main
- [ ] New tag and version release
- [ ] Issues closed
