### ISSUE TITLE
Checklist for version 0.6.2

### ISSUE THREAD

**Issue by verku** [NBISweden/GenErode#92]
- [ ]  Feature branches merged into dev
- [ ]  Test runs finished successfully (github and on cluster)
- [ ]  Changelog updated
- [ ]  Version number updated in Snakefile and config/config.yaml
- [ ]  If needed, pipeline documentation updated
- [ ]  dev merged into main
- [ ]  New tag and version release
- [ ]  Issues closed
